= 2022-07-25_JS__parallax

a new challenge...

They say to chill out for a bit.

So not for me.

It takes me almost a whole day to put all the images neatly over each other.
position, layers,...
add figure in the right place.
Now looking for ome scroll effects
https://workshops.hackclub.com/parallax_effect



day 2 we start with this video: https://www.youtube.com/watch?v=7JtLHJbm0kA

e start an anonymous function in Javascript, that waits fo each element to be loaded before we start the game.
Inhere all the code comes.
 - classes for player, background, enemy and input handlers
- functions to handle the enemy, to display the status of the game, and one to animate the background.

### Class Inputandler:

We make a constructor to keep every pressed button in mind (the arrow keys for start)
if the key is pressed, and not yet in the array of pressed keys (this.keys.indexOf(e.key) === -1), we add i to the array,
whe it's released, we move it from the array (this.keys.splice(this.keys.indexOf(e.key), 1);)

   class InputHandler {
        constructor(){
            this.keys = [];
            window.addEventListener('keydown',e => {
                if ((e.key === 'ArrowDown' ||
                     e.key === 'ArrowUp'||
                     e.key === 'ArrowLeft'||
                     e.key === 'ArrowRight')
                    && this.keys.indexOf(e.key) === -1){
                    this.keys.push(e.key);
                }
            });
            window.addEventListener('keyup',e => {
                if (e.key === 'ArrowDown' ||
                     e.key === 'ArrowUp'||
                     e.key === 'ArrowLeft'||
                     e.key === 'ArrowRight'){
                    this.keys.splice(this.keys.indexOf(e.key), 1);
                }
            });
        }
### player:

we make a class player and give it a play function, to move it around
We prevent it from disappearing from the screen

  if (this.y >= this.gameHeight -this.height) this.y = this.gameHeight -this.height

if (this.x < 0) this.x = 0;
            else if (this.x >this.gameWidth - this.width) this.x = this.gameWidth - this.width


### background:

I take 1 image to make it works
The images moves on the page, when it is finished, it starts again.
Because there is some time te start again,  the  imaged is copied and show after each other, so you don't see it starting again


### enemies:
make a constructor to crate on AND make a function to handle them (create a new one on a different amount of time (interval))
Starting with one, and make an array for multiple enemies














